NAME = SAR_prog



SRC = main.cpp



CC = c++



FLAGS = -Wall -Wextra -Werror -std=c++98



all: $(NAME)




$(NAME):
	$(CC) $(FLAGS) $(SRC) -o $(NAME)



clean:
	rm -rf $(NAME)




fclean: clean




re: fclean all
